language: php

php:
  - 5.4
  - 5.5
#  - 5.6
#  - hhvm

# run build against PHP 5.6 and hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
#matrix:
#  allow_failures:
#    - php: hhvm

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

before_script:
  - mysql -e 'CREATE DATABASE dbTestMain;';
  - mysql -e 'CREATE DATABASE dbTestClient1;';
  - mysql -e 'CREATE DATABASE dbTestClient2;';
  - mysql -e 'CREATE DATABASE dbTestRemote1;';
  - mysql -e 'CREATE DATABASE dbTestRemote2;';

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover