language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

sudo: false

install:
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install --prefer-dist
  - tests/data/travis/apc-setup.sh
  - tests/data/travis/memcache-setup.sh

before_script:
  - mysql -e 'CREATE DATABASE dbTestMain;';
  - mysql -e 'CREATE DATABASE dbTestClient1;';
  - mysql -e 'CREATE DATABASE dbTestClient2;';
  - mysql -e 'CREATE DATABASE dbTestRemote1;';
  - mysql -e 'CREATE DATABASE dbTestRemote2;';

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - cd ../../..
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover